# Generated by Django 5.1.6 on 2025-02-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedores',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
